formatter: "markdown"

# Tested with this version
# As Majorversion is 0 any change may break
version: ">=0.16.0"

sections:
  hide:
    - header
    - providers

output:
  file: "README.md"
  mode: inject

sort:
  enabled: true
  by: required

content: |-
  {{- define "setDict" -}}
    {{- $resource := list -}}
    {{- if hasKey .Dict .Key -}}
      {{- $resource = get .Dict .Key -}}
    {{- else -}}
       {{- $resource = list -}}
    {{- end -}}
    {{- $resource := append $resource .Resource -}}
    {{- $_ := set .Dict .Key $resource -}}
  {{- end -}}
  
  {{- $filesResources := dict -}}
  {{- $resourceTypes := dict -}}
  {{- range .Module.Resources -}}
    {{- template "setDict" dict "Dict" $filesResources "Key" .Position.Filename "Resource" . -}}
    {{- $isResource := eq "resource" (printf "%s" .GetMode) -}}
    {{- if $isResource -}}
      {{- template "setDict" dict "Dict" $resourceTypes "Key" (printf "%s_%s" .ProviderName .Type) "Resource" . -}}
    {{- end -}}
  {{- end -}}
  {{ indent 0 "#" }} Usage
  
  This Module creates a GCP Project
  ```hcl
  {{ include "examples/basic/main.tf" }}
  {{ include "examples/basic/variables.tf" }}
  ```

  This Module creates a GCP Project with automating Cloud Encrypter/Decrypter Role with KMS
  It is possible to include yaml config files.
  ```hcl
  {{ include "examples/crypto/main.tf" }}
  {{ include "examples/crypto/variables.tf" }}
  ```

  This Module creates a GCP Project with a IAM
  ```hcl
  {{ include "examples/iam/main.tf" }}
  {{ include "examples/iam/variables.tf" }}
  ```

  This Module creates a GCP Project with org policies
  ```hcl
  {{ include "examples/organization_policies/main.tf" }}
  {{ include "examples/organization_policies/variables.tf" }}
  ```
  
  ```yaml
  {{ include "examples/organization_policies/configs/boolean.yaml" }}
  ``` 

  This Module creates a GCP Project as a shared vpc host
  ```hcl
  {{ include "examples/shared_vpc/main.tf" }}
  {{ include "examples/shared_vpc/variables.tf" }}
  ```

  This Module creates a GCP Project with sink for logging
  ```hcl
  {{ include "examples/sinks/main.tf" }}
  {{ include "examples/sinks/variables.tf" }}
  ```

  This Module creates a GCP Project with tags
  ```hcl
  {{ include "examples/tags/main.tf" }}
  {{ include "examples/tags/variables.tf" }}
  ```

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ if .Config.Sections.Resources -}}
    {{- if not (keys $resourceTypes) -}}
        {{- if not .Config.Settings.HideEmpty -}}
            {{- indent 0 "#" }} Resource types
            No resources.
        {{ end }}
      {{ else }}
        {{ indent 0 "#" }} Resource types
        | Type | Used |
        |------|-------|
        {{- range $type,$resources := $resourceTypes }}
          {{- $url := (first $resources).URL -}}
          {{- $type = ternary $url (printf "[%s](%s)" $type $url) $type }}
          | {{ $type }} | {{ len $resources }} |
        {{- end }}
        **`Used` only includes resource blocks.** `for_each` and `count` meta arguments, as well as resource blocks of modules are not considered.
      {{ end }}
  {{ end -}}
  {{ .Modules }}
  {{ if or .Config.Sections.Resources .Config.Sections.DataSources -}}
      {{- if not (keys $filesResources) -}}
          {{- if not .Config.Settings.HideEmpty -}}
              {{ indent 0 "#" }} Resources by Files
              No resources.
          {{ end }}
      {{ else }}
          {{ indent 0 "#" }} Resources by Files
          {{- range $fileName,$resources := $filesResources }}
              {{ indent 1 "#" }} {{ $fileName }}
              | Name | Type |
              |------|------|
              
              {{- range $resources -}}
                {{- $isResource := and $.Config.Sections.Resources ( eq "resource" (printf "%s" .GetMode)) }}
                {{- $isDataResource := and $.Config.Sections.DataSources ( eq "data source" (printf "%s" .GetMode)) }}
                {{- if or $isResource $isDataResource }}
                    {{- $fullspec := ternary .URL (printf "[%s](%s)" .Spec .URL) .Spec }}
                    | {{ $fullspec }} | {{ .GetMode }} |
                {{- end }}
              {{- end -}}
          {{- end }}
      {{ end }}
  {{- end -}}